**Часть 1**

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;<br>
   Число строк не равно числу столбцов. Вариантов перемножения нет
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;<br>
   АхВ = 2х3
       
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;<br>
   АхВ = 8х8<br>
   ВхА = 3х3
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.<br>
   АхВ = 4х4<br>
   ВхА = 4х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$

In [1]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица А+В=\n{A+B}')

Матрица А+В=
[[ 5 -3]
 [ 3  5]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=\begin{pmatrix}
3*1-2*0+4*2 & 3*7-2*5+4*(-4)\\ 
3*3-2*2+4*1 & (-6)*3-2*(-1)+4*1
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'3А-2В+4C=\n{3*A-2*B+4*C}')

3А-2В+4C=
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$.<br>
$AA^{T}=\begin{pmatrix}
4*4+1*1 & 4*5+1*(-2) & 4*2+1*3\\ 
5*4+(-2)*1 & 5*5+(-2)*(-2) & 5*2+(-2)*3\\
2*4+3*1 & 2*5+3*(-2) & 2*2+3*3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$<br> 
$A^{T}A=\begin{pmatrix}
4*4+5*5+2*2 & 4*1+5*(-2)+2*3\\ 
1*4+(-2)*5+3*2 & 1*1+(-2)*(-2)+3*3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$.

In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A*AT=\n{np.dot(A, A.T)}\n AT*A=\n{np.dot(A.T, A)}')

A*AT=
[[17 18 11]
 [18 29  4]
 [11  4 13]]
 AT*A=
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [4]:
def mult(A, B):
    A = A
    B = B
    BT = B.T
    if A.shape[1] != B.shape[0]:
        print("ERROR! Matrices dimension is incompatible")
    else:
        i = 0
        j = 0
        M = np.full(shape=[A.shape[0],B.shape[1]], fill_value=1, dtype=np.int)
        while True:
            while True:
                N = A[i]*BT[j]
                M[i][j] = N.sum()
                j += 1
                if j > (BT.shape[0]-1):
                    break
            i += 1
            j = 0
            if i > (A.shape[0]-1):
                    break
        print(M)

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3], [1, 1], [1, 1], [2, 3], [1, 1], [1, 1], [1, 1]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3],
       [ 1,  1],
       [ 1,  1],
       [ 2,  3],
       [ 1,  1],
       [ 1,  1],
       [ 1,  1]])

In [6]:
B = np.array([[5, 3, 6, 7, 10, 1], [6, 1, 2, 11, 54, 12]])
B

array([[ 5,  3,  6,  7, 10,  1],
       [ 6,  1,  2, 11, 54, 12]])

In [7]:
np.dot(A,B)

array([[ 26,  13,  26,  39,  94,  16],
       [ 13,  13,  26,  13, -58, -19],
       [ 28,   9,  18,  47, 182,  38],
       [ 11,   4,   8,  18,  64,  13],
       [ 11,   4,   8,  18,  64,  13],
       [ 28,   9,  18,  47, 182,  38],
       [ 11,   4,   8,  18,  64,  13],
       [ 11,   4,   8,  18,  64,  13],
       [ 11,   4,   8,  18,  64,  13]])

In [8]:
L = mult(A,B)

[[ 26  13  26  39  94  16]
 [ 13  13  26  13 -58 -19]
 [ 28   9  18  47 182  38]
 [ 11   4   8  18  64  13]
 [ 11   4   8  18  64  13]
 [ 28   9  18  47 182  38]
 [ 11   4   8  18  64  13]
 [ 11   4   8  18  64  13]
 [ 11   4   8  18  64  13]]


**Часть 2**

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sin^2x+cos^2x=1;$$

In [9]:
x = 1
A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
print(f'det|A|=\n{np.linalg.det(A):.0f}')

det|A|=
1


б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4*5*9=180;$$

In [10]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'det|A|=\n{np.linalg.det(A):.0f}')

det|A|=
180


 в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=1*5*9+2*6*7+4*8*3-3*5*7-2*4*9-8*6*1=0.$$

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'det|A|=\n{np.linalg.det(A):.0f}')

det|A|=
-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})=16$;

In [12]:
A = np.array([[10, 2], [3, 1]])
print(f'det|A|=\n{np.linalg.det(A):.0f}')

det|A|=
4


In [13]:
print(f'det|A^2|=\n{np.linalg.det(np.dot(A,A)):.0f}')

det|A^2|=
16


   б) $det(A^{T})=4$;

In [14]:
print(f'det|AT|=\n{np.linalg.det(A.T):.0f}')

det|AT|=
4


   в) $det(2A)=16$.

In [15]:
print(f'det|2A|=\n{np.linalg.det(2*A):.0f}')

det|2A|=
16


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}=(-1)^2*(-2)*((-14)*13-6*7)+(-1)^3*7*(4*13-6*(-3))+(-1)^4*(-3)*(4*7-(-14)*(-3))=0$$
det матрицы равен 0 - матрица вырожденная

In [16]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'det|A|=\n{np.linalg.det(A):.0f}')

det|A|=
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} \approx \begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & 0 & 0
\end{pmatrix};$
Ранг матрицы = 2

In [17]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(A)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}\approx \begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1\\ 
0 & 0 & 0 & 0
\end{pmatrix};$
Ранг матрицы = 3

In [18]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(A)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
